Bug/properly configure ballots
telosnetwork/app-telos-net pull request #54
Opened 2022-07-20 18:40 UTC by DevArtemNuss

2022-07-20 23:11 UTC, karynemayer requested changes
@DevArtemNuss you did an amazing job understanding all the new concepts from EOSIO blockchain and the requirements for fixing this bug. ❤️

I left a question for you and a few suggestions for the code. Any comment I left you feel it doesn't make sense, you're more than welcome to question it and make your own suggestions.

2022-07-20 23:11 UTC, karynemayer commented on src/store/trails/actions.js
> +        actions.splice(2, 0, togglebal)
Would it be possible to apply a single `actions.splice(2, 0, togglebal)` at line 242? I think that way, we could focus on defining `togglebal` from line 192 up to 242, and then assign it to `actions`. Do you think it makes sense?

2022-07-21 15:53 UTC, DevArtemNuss commented on src/pages/trails/ballots/components/ballot-form.vue
> +        return this.treasuries.find(t => (t.access === 'public' || t.manager === this.account) && t.symbol === this.form.treasurySymbol.symbol).settings.find(i => i.key === 'stakeable').value
I check settings for current treasury and take config for this

2022-07-21 16:38 UTC, karynemayer commented on src/pages/trails/ballots/components/ballot-form.vue
> +        return this.treasuries.find(t => (t.access === 'public' || t.manager === this.account) && t.symbol === this.form.treasurySymbol.symbol).settings.find(i => i.key === 'stakeable').value
I see!
My only suggestion for readability would be to break this return statement a bit.

```
let selectedTreasurySettings = this.treasuries.find(t => (t.access === 'public' || t.manager === this.account) && t.symbol === this.form.treasurySymbol.symbol)?.settings
return selectedTreasurySettings.find(i => i.key === 'stakeable')?.value
```

Adding the `?` will protect us from throwing an error and breaking the application if, for some obscure reason, we don't get any result from the `find` function.

2022-07-21 18:07 UTC, karynemayer approved these changes
🙌

2022-07-21 18:32 UTC, DonaldPeat requested changes

2022-07-21 18:32 UTC, DonaldPeat commented on src/store/trails/actions.js
> +          }
It looks like all of the `togglebal ` objects are the same except for `setting_name`, you _could_ add a method to return that object passing that value.

2022-07-22 16:58 UTC, DonaldPeat requested changes

2022-07-22 16:58 UTC, DonaldPeat commented on src/store/trails/actions.js
> +              setting_name: i
you can use the same object here just setting the `setting_name`

2022-07-22 19:15 UTC, DonaldPeat approved these changes

2022-07-22 19:15 UTC, merged