hide links and hide btns fot unauthorized
telosnetwork/app-telos-net pull request #68
Opened 2022-08-15 13:36 UTC by DevArtemNuss

2022-08-15 19:16 UTC, donnyquixotic requested changes

2022-08-15 19:16 UTC, donnyquixotic commented on src/boot/ual.js
>  import { KeycatAuthenticator } from '@telosnetwork/ual-telos-keycat'
remove `KeycatAuthenticator`, it is not longer supported

2022-08-15 19:16 UTC, donnyquixotic commented on src/boot/ual.js
>      new KeycatAuthenticator([mainChain]),
remove

2022-08-16 20:05 UTC, donnyquixotic approved these changes

2022-08-16 23:04 UTC, karynemayer approved these changes

2022-08-16 23:06 UTC, merged