Feat/create window for voters details
telosnetwork/app-telos-net pull request #69
Opened 2022-08-15 15:02 UTC by DevArtemNuss

2022-08-16 20:11 UTC, donnyquixotic requested changes

2022-08-16 20:11 UTC, donnyquixotic commented on src/pages/trails/ballots/view/ballot-view.vue
> +                span.text-weight-bold {{ ballot.total_raw_weight.split(' ')[1]  }}&nbsp
maybe create a method/property to parse the desired weight and return as a single value in a single span?

2022-08-17 16:56 UTC, donnyquixotic submitted a review, later dismissed

2022-08-17 23:54 UTC, karynemayer requested changes
Nice! On 🔥

2022-08-17 23:54 UTC, karynemayer commented on src/pages/trails/ballots/view/ballot-view.vue
> +      console.log(this.voters)
I think we should remove this before merging

2022-08-23 16:07 UTC, karynemayer approved these changes

2022-08-24 16:38 UTC, merged